import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { getServerSession } from 'next-auth';

import SessionProvider from '~/app/_components/SessionProvider';
import TopNav from './_components/TopNav';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'My NextJs Blog',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={`font-sans ${inter.className} flex-col gap-4`}>
        <SessionProvider session={session}>
          <TopNav />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
