import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { getServerSession } from 'next-auth';

import SessionProvider from '~/components/SessionProvider';
import TopNav from '~/components/TopNav';
import { ThemeProvider } from '~/components/theme-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'My NextJs Blog',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={`bg-background font-sans ${inter.className} antialiased flex-col gap-4`}>
        <SessionProvider session={session}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <TopNav />
            {children}
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
